### ISSUE TITLE
shell-env couldn't get current shell?

### ISSUE THREAD

**Issue by zcmgyu** [sindresorhus/shell-env#15]
OS: macOS 10.14.3
Shell: zsh
Application environment: ElectronJS
shell-env: 3.0.0

```
$ echo $SHELL
-> /bin/zsh
```

What I get from shell-env's sync() function is 

> Apple_PubSub_Socket_Render: "/private/tmp/com.apple.launchd.XXXXXMj6/Render"
> HMR_HOSTNAME: "localhost"
> HMR_PORT: "0"
> HOME: "/Users/XXXXX"
> LOGNAME: "XXXXX"
> PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/node_modules/.bin:/Applications/Server.app/Contents/Frameworks/Server Helper.app/Contents/MacOS"
> PWD: "/"
> SHELL: "/bin/bash"
> SHLVL: "1"
> SSH_AUTH_SOCK: "/private/tmp/com.apple.launchd.XXXXX/Listeners"
> TMPDIR: "/var/folders/rg/XXXXXX/T/"
> USER: "XXXXX"
> XPC_FLAGS: "0x0"
> XPC_SERVICE_NAME: "0"
> _: "/usr/bin/env"
> __CF_USER_TEXT_ENCODING: "0x1F5:0x0:0x0"

And it seems like shell-env is recognizing that shell is `/bin/bash`, instead of `/bin/zsh`

**Comment by sindresorhus** [comment]
There's no way to know that you're running from `zsh`, as per the readme, Electron and all GUI apps on macOS don't inherit environment variables. So when this module is executed, it has no `SHELL` environment variable, so it defaults to the system default, which is Bash.

**Comment by zcmgyu** [comment]
Thanks you. I will work around by get from all shells

**Comment by silverwind** [comment]
This should be fixed when https://github.com/sindresorhus/default-shell/issues/3 is implemented. If the user shell is set up via `chsh`, `os.userInfo` will return the correct shell.

**Comment by zcmgyu** [comment]
Thanks @silverwind 
As your suggestion, currently it has worked.

```
const os = require('os');
const shellEnv = require('shell');

const { shell } = os.userInfo();

shellEnv.sync(shell);
```
