### ISSUE TITLE
Mention in the documentation that it reads environment variables from an interactive login shell

### ISSUE THREAD

**Issue by jeffcrouse** [sindresorhus/shell-env#18]
On my mac, this module does *not* load .bashrc as the README suggests.  It took me a few hours to track this down, but the -ilc in `/bin/bash -ilc env` (used in index.js) makes bash act like an interactive login shell, which means that it *only* reads from .bash_profile. I assumed (wrongly) that a script within a node GUI app would be considered a non-login shell, hence I expected it to load from .bashrc. 

zsh seems to behave differently.  When I run ` /bin/zsh -ilc env` on my mac, it loads variables from .zshenv, .zprofile, and .zshrc. Weird. 

Anyway, I think it would be helpful for other users to understand that, in bash, this module only loads variables from files that are sourced in an interactive login shell, ie .bash_profile.

PS: Note that this is complicated by the confusing bash/zsh situation on Mac at the moment.  For instance, if your default shell is bash, but then you run `/bin/zsh -ilc env` it will include bash environment variables, presumably because the parent shell is bash... confusing. Also, it seems that you have to log out after running `chsh -s /bin/bash` (as opposed to simply closing a terminal window) to fully change the default shell. Also, just changing the "shells open with command" in Terminal preferences (as some articles suggest) doesn't work. Wow, exciting morning.

**Comment by sindresorhus** [comment]
I have mentioned this in the readme. PR welcome if you think it could be written better/clearer.
