### ISSUE TITLE
error with zsh

### ISSUE THREAD

**Issue by saltfish666** [sindresorhus/shell-env#9]
platform: macOS
node-v : 8.7.0
shell:zsh

if the user is using zsh,zsh will return a useless header without `\n`

(last-4 line)

<img width="1032" alt="screen shot 2018-06-18 at 9 09 15 pm" src="https://user-images.githubusercontent.com/37469825/41537718-debac580-733b-11e8-91ba-4f1d96d9a73a.png">

```
$  env
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
LC_CTYPE=UTF-8
TMPDIR=/var/folders/vm/n4myfnyx0gxc0pt2vgqgqhzc0000gn/T/
TERM_SESSION_ID=A43B3347-56E7-4DAE-ABCD-D71D2CF41455
XPC_FLAGS=0x0
NVM_DIR=/Users/apple/.nvm
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Q48wBxmpsU/Render
TERM=xterm-256color
DISPLAY=/private/tmp/com.apple.launchd.mBmoCyYbF9/org.macosforge.xquartz:0
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.O8b6Urp7ot/Listeners
SECURITYSESSIONID=186a6
GOPATH=/Users/apple/go/src/calcproj
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=388.1.1
PWD=/Users/apple/Desktop/666git/shell-env-t
SHLVL=2
_=/usr/bin/env
M2_HOME=/Users/apple/Downloads/apache-maven-3.5.3
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
SHELL=/bin/zsh
HOME=/Users/apple
LOGNAME=apple
USER=apple
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS
OLDPWD=/Users/apple/Desktop/666git/shell-env-t
ZSH=/Users/apple/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
```
follows is my test to modules `execa`

<img width="768" alt="screen shot 2018-06-18 at 10 31 04 pm" src="https://user-images.githubusercontent.com/37469825/41549204-a74e06a4-7357-11e8-9e7e-b0a8963f3868.png">
<img width="640" alt="screen shot 2018-06-18 at 10 31 21 pm" src="https://user-images.githubusercontent.com/37469825/41549207-a8f59f6c-7357-11e8-8704-ed147d02656e.png">

**Comment by silverwind** [comment]
Show the output of `env` from your shell.

**Comment by silverwind** [comment]
Fixed in https://github.com/sindresorhus/shell-env/commit/f4676bf65cd45c058c207d94ca5d2c255b51d0f7.
